#include<stdio.h>
/****************************************************************************************************************

Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

****************************************************************************************************************/
unsigned long standardImplementation(){
    unsigned long   fib0=1,
                    fib1=1,
                    fib2=fib0+fib1,
                    sum=0;
    while(fib2 < 4000000 ){
        if(fib2 % 2 == 0){
            sum+=fib2;
        }
        fib0=fib1;
        fib1=fib2;
        fib2=fib0+fib1;
    }
    return sum;
}



int E(unsigned long n){
/*
If we only write the even numbers:
2  8 34 144...
it seems that they obey the following recursive relation: E(n)=4*E(n-1)+E(n-2).
*/
    if(n==1)
        return 2;
    if(n==2)
        return 8;

    return 4*E(n-1)+E(n-2);
}

unsigned long efficientImplementation(){
    unsigned long sum = 0 , ctr=0 , val = E(++ctr) ;
    while( val < 4000000 ){
        sum+=val;
        val = E(++ctr) ;
    }
    return sum;
}

int main(){

    printf("%lu \n",standardImplementation());
}
