/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteuler.solutions;

import projecteuler.Problem;

/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * @author gautam
 */
public class Problem2 extends Problem {
    long 
            sum  =0L,
            a = 0L ,
            b = 1L,
            c;
    

    public Problem2() {       
        
        while (b < 4000000L)
        {
            sum+=c;
            a=b+c;
            b=c+a;
            c=a+b;
        }
    }

    

    @Override
    public String toString() {
        return "The sum is :"+ sum;
    }
    
    
}
